### ISSUE TITLE
managing albums basics

### ISSUE THREAD

**Issue by Sulfiore** [libospl/libospl#20]
This means

- [x] create album
- [x] delete album 
- [x] rename album
- [x] assign album to a collection (needs #21 to be done)
- [x] move an album from a collection to another (needs #21 to be done)
- [x] assign a photo to an album (needs #22 to be done)
- [x] documentation
- [x] tests
