### ISSUE TITLE
manage listing

### ISSUE THREAD

**Issue by Sulfiore** [libospl/libospl#25]
this means:

- [x] list thumbails (return a tuple with only the id and the path to the thumbnail) (needs #22)
- [x] list photos (needs #22)
- [x] list collections (needs #21)
- [x] list albums inside a collection (needs #21 and #20)
- [x] list photos inside an album (needs #22 and #20)
- [x] documentation
- [ ] tests
